compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard
  - level: discard
    pattern: '@workspace:examples'
  - level: discard
    pattern: '@storybook/root@workspace:.'
  - level: discard
    pattern: '@workspace:addons/storyshots/'

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: ../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: ../.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

unsafeHttpWhitelist:
  - localhost

yarnPath: ../.yarn/releases/yarn-3.3.0.cjs
installStatePath: '../.yarn/code-install-state.gz'
