name: Unit tests

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Core Unit Tests node-${{ matrix.node_version }}, ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: install and compile
        run: yarn task --task compile --start-from=auto --no-link
      - name: test
        run: yarn test --runInBand --ci
